plugins {
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
    id 'org.spongepowered.mixin' version '0.7-SNAPSHOT'
}

group = mod_group_id
version = mod_version

base {
    archivesName = 'jem-world-boss-tiers'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: 'official', version: minecraft_version
}

repositories {
    mavenCentral()
}

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
}

mixin {
    add sourceSets.main, 'jem_world_boss_tiers.refmap.json'
    config 'jem_world_boss_tiers.mixins.json'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

jar {
    manifest {
        attributes([
                'Specification-Title': mod_id,
                'Specification-Vendor': 'Siirio',
                'Specification-Version': '1',
                'Implementation-Title': project.name,
                'Implementation-Version': archiveVersion,
                'Implementation-Vendor': 'Siirio',
                'MixinConfigs': 'jem_world_boss_tiers.mixins.json'
        ])
    }
    finalizedBy 'reobfJar'
}

tasks.withType(Test).configureEach { enabled = false }
