entityOcclusion = true
blockEntityOcclusion = true
particleOcclusion = true
adaptiveDistance = true
adaptiveEntityDistance = true
adaptiveBlockEntityDistance = true
gpuTiming = true
telemetry = false
leafGapCulling = true
#Allowed Values: PERFORMANCE, BALANCED_PERFORMANCE, QUALITY, CUSTOM
shaderPreset = "PERFORMANCE"
#Range: 30 ~ 240
targetFps = 240
#Allowed Values: CONSERVATIVE, BALANCED, AGGRESSIVE
performancePolicy = "BALANCED"
#Allowed Values: AUTOMATIC, CONSERVATIVE, NEVER_CULL
compatibilityMode = "AUTOMATIC"

