plugins {
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
}

group = 'com.justenoughmods'
version = '1.0.0-dev'

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: 'official', version: '1.20.1'
}

repositories {
    mavenCentral()
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.20.1-47.4.10'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 17
}

jar {
    archiveBaseName = 'jem-villager-talking'
    manifest {
        attributes([
            'Specification-Title': 'JEM Villager Talking',
            'Specification-Version': project.version,
            'Implementation-Title': project.name,
            'Implementation-Version': project.version
        ])
    }
    finalizedBy 'reobfJar'
}

tasks.withType(Test).configureEach { enabled = false }
