modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="create"
mandatory=false
versionRange="[6.0.8,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="jade"
mandatory=false
versionRange="[11,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="jei"
mandatory=false
versionRange="[15,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="jem_world_boss_tiers"
mandatory=true
versionRange="[2.0.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="enhancedai"
mandatory=false
versionRange="[3.3.7.3,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="block_factorys_bosses"
mandatory=false
versionRange="[2.1.2,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="aquamirae"
mandatory=false
versionRange="[7.1.13,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="cataclysm"
mandatory=false
versionRange="[3.31,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="backtobed"
mandatory=false
versionRange="[1.1.0,)"
ordering="AFTER"
side="BOTH"
