entityOcclusion = true
blockEntityOcclusion = true
#Range: 9 ~ 144
raysPerWindow = 48
#Range: 100 ~ 2000
microsecondsPerWindow = 500
#Range: 16 ~ 128
maxOcclusionDistance = 64
#Allowed Values: AUTOMATIC, CONSERVATIVE, NEVER_CULL
compatibilityMode = "AUTOMATIC"

